source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Using ActiveAdmin for various features
# The additional gems are to ensure full compatability with rails 4.0
# They come from seanlinsley's recommendation on https://github.com/gregbell/active_admin/issues/2322
# After a failure to bundle install, I removed most of them save for ransack, and bundle install worked
gem 'activeadmin',         github: 'gregbell/active_admin'
gem 'ransack'             # github: 'ernie/ransack'
# gem 'inherited_resources', github: 'josevalim/inherited_resources'
# gem 'formtastic',          github: 'justinfrench/formtastic'

# Use CarrierWave to upload files (.pdf files in this application)
gem 'carrierwave'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'puma'